on: workflow_call

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - uses: actions/cache@v4
        id: yarn-cache
        with:
          path: |
            ${{ github.workspace }}/node_modules
            ${{ github.workspace }}/.yarn/cache
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}-nodemodules
      - name: Install packages
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install --immutable

  check:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ${{ github.workspace }}/node_modules
            ${{ github.workspace }}/.yarn/cache
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}-nodemodules
      - name: tsc/lint/format check
        run: yarn tsc && yarn run biome ci .
