name: check

on:
  push:
    branches: "!main"

jobs:
  ci:
    uses: ./.github/workflows/_ci.yml

  build:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ${{ github.workspace }}/node_modules
            ${{ github.workspace }}/.yarn/cache
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}-nodemodules
      - uses: actions/cache@v3
        id: build-cache
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}-next-build-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}-next-build-
      - name: Run build
        if: steps.build-cache.outputs.cache-hit != 'true'
        run: yarn turbo build
        env:
          NODE_ENV: development

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
